id: opecha:P004371
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9771
  title: སྡེ་དགེ་པར་ཁང་གི་དཀར་ཆག་ཞིབ་རྒྱས་སུ་བཀོད་པ་ཤེས་བྱའི་སྒོ་འབྱེད། ༼སི་ཁྲོན་མི་རིག་དཔེ་སྐྲུན་ཁང་།༽
  volume: ''
  author: ''
